version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - revive
  settings:
    revive:
      rules:
        - name: exported

formatters:
  enable:
    - gofmt
    - goimports
