name: code quality
on: [push, pull_request]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: [1.16, 1.22, 1.24]
    steps:
      - name: Set up Go ${{ matrix.go-version}}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version}}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go mod download

      - name: Run tests
        run: |
          go test -race -coverprofile=coverage.txt -covermode=atomic